plugins { id 'com.android.application' }

android {
    namespace 'com.den.lilytoggle'
    compileSdk 35

    defaultConfig {
        applicationId 'com.den.lilytoggle'
        minSdk 26
        targetSdk 28
        versionCode 4
        versionName '4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
